# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - oldrel
  - release
  - devel
r_github_packages:
  - s-fleck/lgrExtra
sudo: false
after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'devtools::install();devtools::test()'
