# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r_binary_packages:
  - devtools
  - roxygen2
services:
  - postgresql
after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'devtools::install();devtools::test()'
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
