# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# https://gist.github.com/gaborcsardi/68960fb01bec74d89611bb9c2b0b7e5a
language: R
matrix:
  include:
  - r: devel
  - r: release
    before_cache:
      - Rscript -e 'remotes::install_cran("pkgdown")'
    after_success:
      - Rscript -e 'covr::codecov()'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github(ssh_id = Sys.getenv("TRAVIS_DEPLOY_KEY", ""))'
      skip_cleanup: true
  - r: 3.5
  - r: 3.4
  - r: 3.3
  - r: 3.2
  - r: 3.1
    before_cache:
      - Rscript -e 'remotes::install_cran("curl")'
  - r: 3.0
      before_cache:
      - Rscript -e 'remotes::install_cran("curl")'
r_github_packages:
  - s-fleck/lgrExtra
sudo: false
after_success:
  - Rscript -e 'devtools::install();devtools::test()'
