# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - oldrel
  - release
  - devel
r_github_packages:
  - s-fleck/lgr.app
sudo: false
after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'devtools::install();devtools::test()'
